//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkue
    {
        public int id { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_tickets { get; set; }
        public Nullable<System.DateTime> datebuy { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual tickets tickets { get; set; }
        public virtual users users { get; set; }
    }
}
