//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class holl_busy
    {
        public int id { get; set; }
        public Nullable<int> id_holl { get; set; }
        public Nullable<int> id_holl_status { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual holls holls { get; set; }
        public virtual status_holl status_holl { get; set; }
    }
}
