//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class rows
    {
        public string id { get; set; }
        public Nullable<int> id_holl { get; set; }
        public Nullable<int> columns { get; set; }
        public Nullable<int> rows1 { get; set; }
    }
}
