//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tickets()
        {
            this.checkue = new HashSet<checkue>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_sessions { get; set; }
        public string row { get; set; }
        public string columns { get; set; }
        public Nullable<int> id_holl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkue> checkue { get; set; }
        public virtual holls holls { get; set; }
        public virtual sessions sessions { get; set; }
    }
}
